### ISSUE TITLE
BT106 - add createDto class

### ISSUE THREAD

**Issue by MaciejSzczepanczyk** [akademia-envelo-3/meetek-back#170]
### Opis:

- Dodaj klasy do tworzenia obiektów createDto
- Dodaj mappery do utworzonych klas
- refactor klas, używających mappera

### Kryteria akceptacji:
- klasy poprawnie się mapują
- utworzone metody create są poprawione

###  Definicja ukończenia:
- Kryteria akceptacji są spełnione.
- Kod jest sformatowany zgodnie z domyślnym ustawieniem IntelliJ (ctrl+alt+L).
- Kod pomyślnie przeszedł testy jednostkowe.
- Utworzono commit.
- Utworzono pull request.
- Kod pomyślnie przeszedł code review.
- Działanie kodu zostało przetestowane i zaakceptowane przez testera.
- Kod został zmergowany z branch'em dev.

**Comment by mnk-7** [comment]
[Dokument.odt](https://github.com/akademia-envelo-3/meetek-back/files/10570272/Dokument.odt)
