### ISSUE TITLE
BT028 - feat: CRUD survey

### ISSUE THREAD

**Issue by zaborowskim** [akademia-envelo-3/meetek-back#33]
### Wymagania wstępne:
- Ukończone taski: od T007- feat: get events - repositories  do T016 - feat: get events - user, future, public, not accepted, few days
( [Task007](https://github.com/akademia-envelo-3/meetek-back/issues/12) | [Task008](https://github.com/akademia-envelo-3/meetek-back/issues/13) | [Task009](https://github.com/akademia-envelo-3/meetek-back/issues/14) | [Task010](https://github.com/akademia-envelo-3/meetek-back/issues/15) | [Task011](https://github.com/akademia-envelo-3/meetek-back/issues/17) | [Task012](https://github.com/akademia-envelo-3/meetek-back/issues/16) | [Task013](https://github.com/akademia-envelo-3/meetek-back/issues/18) | [Task014](https://github.com/akademia-envelo-3/meetek-back/issues/19) | [Task015](https://github.com/akademia-envelo-3/meetek-back/issues/21) | [Task016](https://github.com/akademia-envelo-3/meetek-back/issues/20) | [TaskBT029](https://github.com/akademia-envelo-3/meetek-back/issues/34)  | [TaskBT030](https://github.com/akademia-envelo-3/meetek-back/issues/35) )

### Opis:
SurveyService:
- utwórz metodę `createSurvey(Survey survey) : Optional<Survey>`
- utwórz metodę `getSurvey(long surveyId) : Optional<Survey>`
- utwórz metodę `deleteSurvey(long surveyId) : void`

SurveyRepository:
- utwórz metodę `save(Survey survey) : Optional<Survey>`
- utwórz metodę `findById(Long surveyId): Optional<Survey>`
- utwórz metodę `deleteById(Long surveyId) : void`

### Kryteria akceptacji:
- metody do tworzenia dodają nową ankietę
- metody do usuwania usuwają ankietę
- metody do pobierania danych wyświetlają odpowiednią ankietę

- kod zostaje zatwierdzony przez więcej niż 1 osobę.

### Definicja ukończenia:
- Kryteria akceptacji są spełnione.
- Kod jest sformatowany zgodnie z domyślnym ustawieniem IntelliJ (ctrl+alt+L).
- Kod pomyślnie przeszedł testy jednostkowe.
- Utworzono commit.
- Utworzono pull request.
- Kod pomyślnie przeszedł code review.
- Działanie kodu zostało przetestowane i zaakceptowane przez testera.
- Kod został zmergowany z branch'em dev.

**Comment by MaciejSzczepanczyk** [comment]
UPDATE
- dodać metody do wyliczania statystyk odpowiedzi w ModelMapperService
- dodać mapę<Long,BigDecimal> choicePercent w SurveyDto 
- dodać dane testowe do Survey/SurveyResponse
